version: '2'
services:
  api:
    extends:
      file: common-services.yml
      service: api
    build:
      context: .
      dockerfile: Dockerfile.runtime
    environment:
    - SECOptions:MongoConnectionString=mongodb://192.168.1.53:27017
    - SECOptions:DatabaseName=secdata
  nginx:
    extends:
      file: common-services.yml
      service: nginx
    links:
    - api
    build:
      context: .
      dockerfile: Dockerfile.nginx
