FROM microsoft/dotnet:1.1.0-runtime

WORKDIR /app
COPY out .

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000


#CMD ["dotnet", "run", "--server.urls", "http://*:5000"]
ENTRYPOINT ["dotnet", "Services.dll"]
